# Generated by Django 6.0.4 on 2026-05-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailwind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
